### ISSUE TITLE
API Domain change

### ISSUE THREAD

**Issue by geromegrignon** [gothinkster/clojurescript-keechma-realworld-example-app#20]
Hello!

Due to governance changes, we are now using the `realworld.io` domain for the RealWorld demo (both client and API).
Requests from `conduit.productionready.io` are redirected to `api.realworld.io`, but such a redirection might lead to inconsistent responses.

We encourage domain change for the community.
If this repository is maintained anymore, we'll consider hosting a demo of your implementation in a few weeks with the domain change.

The demo link will be added to the RealWorld documentation.

**Comment by geromegrignon** [comment]
Demo API URL updated.

**Comment by retro** [comment]
@geromegrignon Just to confirm, this repository is still maintained, and I would appreciate if you would host the demo

**Comment by geromegrignon** [comment]
Hey @retro, great news!

I was about to host it immediately but I'm considering creating a partnership with a hosting provider like Netlify for a sustainable solution (most solutions having either member or apps limitations).
